# Generated by Django 5.2.2 on 2025-06-05 04:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0003_feedback_difficulty_alter_feedback_experience_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='suggestions',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='difficulty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='quality',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='userresponse',
            unique_together={('user', 'test', 'question')},
        ),
    ]
